# PremiumVanish v2.6.2 - Bungeecord proxy extension config
Configuration:  
  Database:
    # The credentials for the database, make sure to use the same database for PV on any bukkit/bungee server.
    # This has to be enabled for this plugin to work on bungeecord.
    Enable: true
    # The ip of your database server
    Ip: ""
    # The port of your database, usually 3306; just leave it empty if there is no specific port
    Port: "3306"
    # You can make PremiumVanish ignore the two options above and use a direct URI to connect instead
    # Format for MySQL servers: jdbc:mysql://<yourIp>:<yourPort>/<yourDatabase>
    #
    # If there are SSL certificate errors in the console, it's likely that your database hasnt setup a proper
    # SSL certificate. This is a security flaw especially if your database is accessible from the internet.
    # You can add ?useSSL=false to the end of a custom URI to suppress such certificate errors.
    CustomURI: ""
    # The name of your database user
    User: ""
    # The password of your database user
    # WARNING: Please make sure only people who are allowed to know the password can access this file
    Password: ""
    # The name of the database which PremiumVanish should create its tables in
    # Note: PremiumVanish won't create this database, it must be pre-created using eg. phpMyAdmin
    Database: ""
    # Not recommended; Makes PV use the standard JDBC connector instead of the more powerful multi-pooled HikariCP one
    # You can give this a try if you have strange problems with connecting to your database
    BasicDatabaseConnector: false
  Features:
    # Should PremiumVanish hide invisible players in the bungeecord commands /glist, /server and /find?
    # Note: You can use 'pv.see' as a bungeecord permission to determine which players should be able to see
    # invisible players in these commands. (This doesn't replace the bukkit permission, it's recommended to use both)
    ReplaceBungeeCommands: true
    # Should PremiumVanish adjust the playercount in the serverlist? (-1 per invisible player)
    AdjustPlayerCount: true
    # Should PremiumVanish remove the names of vanished players from tab-completions for players without pv.see?
    FilterTabCompletions: true
    # You can make any command not execute and instead return a custom message if an argument is a vanished
    # player's name. Useful for faking 'Player not found' messages if there are unsupported plugins.
    # You can use <vanished> as a placeholder for any vanished player's name and <...> as a placeholder for
    # anything but whitespace. Any message which STARTS WITH the text you define below (case-insensitive) will
    # be cancelled and will instead send the sender of the command a message you specify.
    # This is network-wide and not optimized for Bukkit commands, for non-bungeecord commands go to the
    # server's PV config; exempt permission: pv.see
    CustomCommandMessages:
      '/examplemsg1 <vanished>': "&cPlayer not found"
      '/makemeadmin2 group <...> useradd <vanished>': "&c<vanished> is totally not online!"